#!/bin/bash
# Quick Setup Script for Study Planner

echo "🚀 Study Planner - Quick Setup Guide"
echo "===================================="
echo ""
echo "✅ Step 1: Dependencies Installation"
echo "   Status: Running (npm install)"
echo ""
echo "📝 Step 2: Create .env.local"
echo "   Run: cp .env.local.example .env.local"
echo ""
echo "🔑 Step 3: Add Supabase Credentials"
echo "   1. Go to https://supabase.com"
echo "   2. Create a free account and project"
echo "   3. Go to Settings → API"
echo "   4. Copy Project URL"
echo "   5. Copy Anon Key"
echo "   6. Edit .env.local and add:"
echo "      NEXT_PUBLIC_SUPABASE_URL=<your_url>"
echo "      NEXT_PUBLIC_SUPABASE_ANON_KEY=<your_key>"
echo ""
echo "💾 Step 4: Set Up Database"
echo "   1. In Supabase, go to SQL Editor"
echo "   2. Click 'New Query'"
echo "   3. Copy entire content of DATABASE_SETUP.sql"
echo "   4. Paste into SQL Editor"
echo "   5. Click 'Run'"
echo "   6. Wait for success message"
echo ""
echo "🔥 Step 5: Start Development Server"
echo "   Run: npm run dev"
echo ""
echo "🌐 Step 6: Open in Browser"
echo "   Go to: http://localhost:3000"
echo ""
echo "===================================="
echo "📚 Documentation:"
echo "   - GETTING_STARTED.md (detailed checklist)"
echo "   - README.md (full reference)"
echo "   - PROJECT_SUMMARY.md (overview)"
echo "===================================="
